concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
jobs:
  android:
    if: needs.check-env.outputs.browserStackUrl-available == 'true'
    needs:
    - check-env
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
    - continue-on-error: true
      name: Install Fluentlenium
      uses: ./.github/actions/fluentlenium-maven-install
    - continue-on-error: true
      name: E2E on Android Web test (Chrome on Android device)
      run: ./mvnw -B -nsu -Pexamples -pl examples/spring clean test -DbrowserName=android
        -Dmobile.simulator=false -DuseHub=true -DgridUrl=${{ secrets.BROWSER_STACK_URL
        }}
  check-env:
    outputs:
      browserStackUrl-available: ${{ steps.browserStackUrl.outputs.defined }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        URL: ${{ secrets.BROWSER_STACK_URL }}
      id: browserStackUrl
      if: ${{ env.URL != '' }}
      run: echo "defined=true" >> "$GITHUB_OUTPUT"
  chrome:
    if: needs.check-env.outputs.browserStackUrl-available == 'true'
    needs:
    - check-env
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
    - continue-on-error: true
      name: Install Fluentlenium
      uses: ./.github/actions/fluentlenium-maven-install
    - continue-on-error: true
      name: E2E on Chrome
      run: ./mvnw -B -nsu -Pexamples -pl examples/spring clean test -DbrowserName=chrome
        -Dmobile.simulator=false -DuseHub=true -DgridUrl=${{ secrets.BROWSER_STACK_URL
        }}
  edge:
    if: needs.check-env.outputs.browserStackUrl-available == 'true'
    needs:
    - check-env
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
    - continue-on-error: true
      name: Install Fluentlenium
      uses: ./.github/actions/fluentlenium-maven-install
    - continue-on-error: true
      name: E2E on Edge
      run: ./mvnw -B -nsu -Pexamples -pl examples/spring clean test -DbrowserName=edge
        -Dmobile.simulator=false -DuseHub=true -DgridUrl=${{ secrets.BROWSER_STACK_URL
        }}
  firefox:
    if: needs.check-env.outputs.browserStackUrl-available == 'true'
    needs:
    - check-env
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
    - continue-on-error: true
      name: Install Fluentlenium
      uses: ./.github/actions/fluentlenium-maven-install
    - continue-on-error: true
      name: E2E on Firefox
      run: ./mvnw -B -nsu -Pexamples -pl examples/spring clean test -DbrowserName=firefox
        -Dmobile.simulator=false -DuseHub=true -DgridUrl=${{ secrets.BROWSER_STACK_URL
        }}
  ie:
    if: needs.check-env.outputs.browserStackUrl-available == 'true'
    needs:
    - check-env
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
    - continue-on-error: true
      name: Install Fluentlenium
      uses: ./.github/actions/fluentlenium-maven-install
    - continue-on-error: true
      name: E2E on IE
      run: ./mvnw -B -nsu -Pexamples -pl examples/spring clean test -DbrowserName=ie
        -Dmobile.simulator=false -DuseHub=true -DgridUrl=${{ secrets.BROWSER_STACK_URL
        }}
  iphone:
    if: needs.check-env.outputs.browserStackUrl-available == 'true'
    needs:
    - check-env
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
    - continue-on-error: true
      name: Install Fluentlenium
      uses: ./.github/actions/fluentlenium-maven-install
    - continue-on-error: true
      name: E2E on Iphone Web test (Safari on Iphone)
      run: ./mvnw -B -nsu -Pexamples -pl examples/spring clean test -DbrowserName=iphone
        -Dmobile.simulator=false -DuseHub=true -DgridUrl=${{ secrets.BROWSER_STACK_URL
        }}
  safari:
    if: needs.check-env.outputs.browserStackUrl-available == 'true'
    needs:
    - check-env
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
    - continue-on-error: true
      name: Install Fluentlenium
      uses: ./.github/actions/fluentlenium-maven-install
    - continue-on-error: true
      name: E2E on Firefox
      run: ./mvnw -B -nsu -Pexamples -pl examples/spring clean test -DbrowserName=safari
        -Dmobile.simulator=false -DuseHub=true -DgridUrl=${{ secrets.BROWSER_STACK_URL
        }}
name: E2E pipeline
on:
  repository_dispatch:
    types: trigger-ga___e2e-workflow.yml
